# Generated by Django 5.1.2 on 2024-10-27 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_customuser_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='vacancy',
            new_name='number_of_openings',
        ),
    ]
