# Generated by Django 5.1.2 on 2024-10-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_rename_vacancy_jobmodel_number_of_openings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='skills',
            field=models.CharField(choices=[('programming', 'Programming'), ('networking', 'Networking'), ('graphics_design', 'Graphics Design'), ('cyber_security', 'Cyber Security')], max_length=100, null=True),
        ),
    ]
